name: XcodeMini
options:
  deploymentTarget:
    macOS: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.egor.xcodemini
    PRODUCT_NAME: Xcode Mini
    MARKETING_VERSION: 0.0.1
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.0"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Xcode Mini
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.developer-tools
targets:
  XcodeMini:
    type: application
    platform: macOS
    sources:
      - path: Sources
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
